### PR TITLE
Add autoload section for server/php/UploadHandler.php

### PR DESCRIPTION
**Pull request by deatharse**
Autoloads `server/php/UploadHandler.php`

### CODE REVIEW

**Comment by vkhramtsov** [comment]
Is it really needed? Looks like this is only example script.

**Comment by deatharse** [comment]
Well it can be used as-is by passing the correct settings array into its constructor (or extended as desired) and saves people pulling your repo from packagist the need to explicitly add a section in the form:

    "autoload": {
        "classmap": [
            "vendor/blueimp/jquery-file-upload/server/php/UploadHandler.php
        ]
    }

**Comment by jonnybradley** [comment]
Is there any way round this please? We remove this file (actually the whole directory) in a `post-update-cmd` command, and this now breaks composer for us as it fails fatally the second time `composer install` is run.

Is there a way to disable this do you know?

Thanks in advance...

**Comment by vkhramtsov** [comment]
But why do you remove this? Usually vendor dir is out of document root

**Comment by jonnybradley** [comment]
Sadly not in our case :(

**Comment by vkhramtsov** [comment]
hmm... 
I don't know the solution.
If you need only assets, you can use yarn for this

**Comment by vkhramtsov** [comment]
@alasdairdc, Looks like it is better to delegate more to people using this code. Do you have any solution for this situation?

**Comment by deatharse** [comment]
@jonnybradley Why do you remove it?  Is there a naming collision?  There may be a solution depending on the reason and you can then cease removing it.

**Comment by jonnybradley** [comment]
Thanks for your attention, we have resolved the issue now.

**Pull request merged**
